; Configuração PHP recomendada para Moodle 5.x em Docker/Coolify
; Arquivo carregado como /usr/local/etc/php/conf.d/custom.ini

; Recursos
max_input_vars = 5000
memory_limit = 768M
max_execution_time = 300
max_input_time = 300

; Uploads
upload_max_filesize = 1024M
post_max_size = 1024M
max_file_uploads = 20

; Timezone / charset
date.timezone = America/Manaus
default_charset = "UTF-8"

; Produção / segurança
expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT

; Variáveis e sessão
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
session.use_only_cookies = 1
session.use_trans_sid = 0
session.gc_divisor = 1000
session.sid_length = 26
session.sid_bits_per_character = 5

; FastCGI / Moodle
cgi.fix_pathinfo = 1
output_buffering = 4096
zlib.output_compression = Off
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60

; OPcache
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 80000
opcache.revalidate_freq = 60
opcache.validate_timestamps = 1
opcache.save_comments = 1

; Não habilitei JIT.
; Para Moodle, JIT geralmente não é prioridade e pode dificultar diagnóstico.
; opcache.jit_buffer_size = 0
; opcache.jit = 0
